
name: 'SWM GitHub Actions Basic'

on: push

jobs:
  build-test:
    name: 'build test'
    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World
      shell: bash
      run: |
        echo "Hello World"
  deploy-dev:
    name: 'deploy dev'
    needs:
      - build-test
    runs-on: 'ubuntu-latest'

    steps:
    - name: Say Hello World
      shell: bash
      run: |
        echo "Hello World"
  deploy-staging1:
    name: 'deploy staging1'
    runs-on: 'ubuntu-latest'
    needs:
      - deploy-prod
    steps:
    - name: Say Hello World
      shell: bash
      run: |
        echo "Hello World"
  deploy-staging2:
    name: 'deploy staging2'
    runs-on: 'ubuntu-latest'
    needs:
      - deploy-prod
    steps:
    - name: Say Hello World
      shell: bash
      run: |
        echo "Hello World"
  deploy-prod:
    name: 'deploy prod'
    runs-on: 'ubuntu-latest'
    needs:
      - deploy-staging1
      - deploy-staging2
    steps:
    - name: Say Hello World
      shell: bash
      run: |
        echo "Hello World"