
name: 'SWM GitHub Actions Basic'

on: push

# global env
env:
  GLOBAL_LEVEL: 'GLOBAL ENV VALUE' 

jobs:
  first-job:
    name: 'First Job'
    
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest","macos-latest"]
    runs-on: ${{matrix.os}}
    env:
      JOB_LEVEL_1: 'JOB LEVEL VALUE 1'
    steps:
    - name: Say Hello World 1 - ${{matrix..os}}
      shell: bash
      run: |
        echo: "OS: ${{matrix.os}}"
        echo "Hello World from step 1"