
name: 'SWM GitHub Actions Basic'

on: push

# global env
env:
  GLOBAL_LEVEL: 'GLOBAL ENV VALUE' 

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    env:
      JOB_LEVEL_1: 'JOB LEVEL VALUE 1'
    steps:
    - name: Say Hello World 1
      shell: bash
      env:
        STEP_LEVEL_1: 'Step LEVEL VALUE 2'
      run: |
        echo "Hello World from step 1"
        # 쉘 명령어를 이용한 저장
        randomValue="swm(echo $RANDOM)"
        # github action을 이용한 저장
        # $GITHUB_ENV: job를 실행할 때만 동작하는 tmp파일.
        # 동작을 하고 저장한 다음에 다음 step에 전달 가능
        # step level scop를 가진다.
        echo "STEP_VALUE=$randomValue" >> $GITHUB_ENV

    - name: Say Hello World 2
      shell: pwsh
      env:
         STEP_LEVEL_2: 'Step LEVEL VALUE 2'
      run: |
        echo "Hello World from step 2"
        echo "STEP_VALUE: ${{env.STEP_VALUE}}"
