
name: 'SWM GitHub Actions Basic: webec chat bot'

on: push

jobs:
  build-test:
    name: 'build test'
    runs-on: 'ubuntu-latest'

    steps:
    - name: checkout codes
      uses: actions/checkout@v3
    - name: Send a message to Webex Space
      shell: bash
      run: |
        curl -X POST https://webexapis.com/v1/messages \
             -H 'Authorization: Bearer ${{secrets.WEBEX_TOKEN}}' \
             -H 'Content-type: application/json' \
             -d '{
                "roomId":"${{secrets.WEBEX_ROOM_ID}}",
                "text": "test - From Github Action"
              }'
    - name: Post Message to Webex Room
      uses: chrivand/action-webex-js@main
      env:
        WEBEX_TOKEN: ${{ secrets.WEBEX_TOKEN }}
        WEBEX_ROOM_ID: ${{ secrets.WEBEX_ROOM_ID }}
        MARKDOWN_MESSAGE: "**Hello, world! You just ran an action from ${{ github.repository }}.**"
    - name: Send message from custom action to Webex
      uses: ./@gitaction 
      with:
        webexToken: ${{ secrets.WEBEX_TOKEN }}
        webexRoomId: ${{ secrets.WEBEX_ROOM_ID }}
        bodyText: 'test - From Github Action'
        bodyMarkdown: '**Hello, world! You just ran an action from ${{ github.repository }}.**'